"use client";
import { useEffect, useState, type CSSProperties } from "react";

type Level={levelKey:string;displayName:string;visualMode:'colors'|'image';visualPrimary:string;visualSecondary:string;visualAccent:string;visualImageUrl:string|null};
const hex=(value:string,fallback:string)=>/^#[0-9a-fA-F]{6}$/.test(value)?value:fallback;

export default function LoyaltyVisualAdmin(){
  const [levels,setLevels]=useState<Level[]>([]);const [busy,setBusy]=useState("");const [message,setMessage]=useState("");
  useEffect(()=>{fetch('/api/admin/loyalty',{cache:'no-store'}).then(async r=>{const d=await r.json();if(r.ok)setLevels(d.levels||[])}).catch(()=>undefined)},[]);
  const patch=(key:string,p:Partial<Level>)=>setLevels(rows=>rows.map(row=>row.levelKey===key?{...row,...p}:row));
  async function upload(level:Level,file?:File){if(!file)return;setBusy(level.levelKey);setMessage('');try{const fd=new FormData();fd.set('file',file);const r=await fetch('/api/admin/loyalty/visual-upload',{method:'POST',body:fd});const d=await r.json();if(!r.ok)throw new Error(d.error||'Ошибка загрузки');patch(level.levelKey,{visualImageUrl:d.url,visualMode:'image'});setMessage(`Фон ${level.displayName} загружен. Нажми «Сохранить вид».`);}catch(e){setMessage(e instanceof Error?e.message:'Ошибка');}finally{setBusy('')}}
  async function save(level:Level){setBusy(level.levelKey);setMessage('');try{const r=await fetch('/api/admin/loyalty',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({levelKey:level.levelKey,visualMode:level.visualMode,visualPrimary:level.visualPrimary,visualSecondary:level.visualSecondary,visualAccent:level.visualAccent,visualImageUrl:level.visualImageUrl})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Ошибка сохранения');setLevels(rows=>rows.map(row=>row.levelKey===level.levelKey?{...row,...d.level}:row));setMessage(`Вид уровня ${level.displayName} сохранён.`);}catch(e){setMessage(e instanceof Error?e.message:'Ошибка');}finally{setBusy('')}}
  if(!levels.length)return null;
  return <section className="admin-loyalty-visuals-v134"><div className="admin-panel-head"><div><span>ВИЗУАЛ AGAYO ID</span><h2>ВИД ПО УРОВНЮ</h2></div></div><p className="admin-settings-note">Для каждого уровня администратор выбирает либо собственную цветовую гамму, либо изображение-фон. Это меняет карточку AGAYO ID пользователя.</p>{message?<div className="admin-ticket-message-v133">{message}</div>:null}<div className="admin-loyalty-visual-grid-v134">{levels.map(level=><article key={level.levelKey}><div className={`admin-loyalty-preview-v134 ${level.visualMode==='image'?'has-image':''}`} style={{'--lv-primary':hex(level.visualPrimary,'#121214'),'--lv-secondary':hex(level.visualSecondary,'#4B0F19'),'--lv-accent':hex(level.visualAccent,'#C21F39'),backgroundImage:level.visualMode==='image'&&level.visualImageUrl?`linear-gradient(180deg,rgba(8,8,9,.1),rgba(8,8,9,.62)),url("${level.visualImageUrl.replace(/["\\]/g,'')}")`:undefined} as CSSProperties}><span>AGAYO ID</span><b>{level.displayName}</b><strong>A</strong></div><label><span>РЕЖИМ</span><select value={level.visualMode} onChange={e=>patch(level.levelKey,{visualMode:e.target.value==='image'?'image':'colors'})}><option value="colors">Цветовая гамма</option><option value="image">Изображение</option></select></label>{level.visualMode==='colors'?<div className="admin-loyalty-colors-v134">{([['visualPrimary','Основной'],['visualSecondary','Вторичный'],['visualAccent','Акцент']] as const).map(([key,label])=><label key={key}><span>{label}</span><div><input type="color" value={hex(level[key],'#121214')} onChange={e=>patch(level.levelKey,{[key]:e.target.value})}/><input value={level[key]} maxLength={7} onChange={e=>patch(level.levelKey,{[key]:e.target.value})}/></div></label>)}</div>:<label className="admin-loyalty-upload-v134"><span>ИЗОБРАЖЕНИЕ</span><input type="file" accept="image/*" disabled={busy===level.levelKey} onChange={e=>void upload(level,e.target.files?.[0])}/><small>{level.visualImageUrl?'Фон загружен':'JPG / PNG / WEBP · до 10 МБ'}</small></label>}<button className="admin-primary" disabled={busy===level.levelKey} type="button" onClick={()=>void save(level)}>{busy===level.levelKey?'СОХРАНЯЕМ…':'Сохранить вид'}</button></article>)}</div></section>;
}
